---

- hosts: 172.69.11.82
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    auto_ipl: true
    pre_reboot_delay: 60
    post_reboot_delay: 60
    reboot_timeout: 1800
    connect_timeout: 300
    test_command: 'uname'
    msg: 'Reboot initiated by Ansible'
    how_to_end: '*IMMED'
    controlled_end_delay_time: 600
    reboot_type: '*IPLA'
    ipl_source: '*PANEL'
    end_subsystem_option: '*DFT'
    timeout_option: '*CONTINUE'
    parameters: ''

    jobs:
      - name: Reboot the system immediately if auto_ipl is set to true and at least one PTF requires an IPL
        ibm_reboot:
          pre_reboot_delay: '{{ pre_reboot_delay }}'
          post_reboot_delay: '{{ post_reboot_delay }}'
          reboot_timeout: '{{ reboot_timeout }}'
          connect_timeout: '{{ connect_timeout }}'
          test_command: '{{ test_command }}'
          msg: '{{ msg }}'
          how_to_end: '{{ how_to_end }}'
          controlled_end_delay_time: '{{ controlled_end_delay_time }}'
          reboot_type: '{{ reboot_type }}'
          ipl_source: '{{ ipl_source }}'
          end_subsystem_option: '{{ end_subsystem_option }}'
          timeout_option: '{{ timeout_option }}'
        
        when: auto_ipl | bool
