---
  name: Sync and apply ptf group files
# This playbook will transfer the ptf group files to the target system according to the giving ptf group directory. Then apply the ptf group.

# Command example: ansible-playbook /sync_apply_ptf_group_using_filedir.yml -e "{'target_system': 'systemA', 'repo_server': 'systemB',
# 'ptf_group_dir': '/tmp/SF99729_125', 'delete': true}"
# The 'delete' parameter specifies whether or not to delete the file install dir on target server after apply. The default value is true.
  hosts: '{{ target_system }}'
  gather_facts: false
  collections:
    - ibm.power_ibmi

  vars:
    repo_server: "{{ repo_server }}"
    deletefile: "{{ delete | default(true) }}"
    auto_ipl: false
    pre_reboot_delay: 60
    post_reboot_delay: 60
    reboot_timeout: 1800
    connect_timeout: 300
    test_command: 'uname'
    msg: 'Reboot initiated by Ansible'
    how_to_end: '*IMMED'
    controlled_end_delay_time: 600
    reboot_type: '*IPLA'
    ipl_source: '*PANEL'
    end_subsystem_option: '*DFT'
    timeout_option: '*CONTINUE'
    parameters: ''

  tasks:
    - name: Recursively find ptf group files
      find:
        paths: "{{ ptf_group_dir }}"
        recurse: true
      delegate_to: "{{ repo_server }}"
      register: find_result

    - name: Print find_result
      debug:
        var: find_result

    - name: quit
      fail:
        msg: "ptf_group_dir: {{ ptf_group_dir }} is not valid or doesn't contain any file, quit."
      when: find_result.matched == 0

    - name: Compose target tmp dir str
      set_fact:
        path: "~/PTF/{{ ptf_group_dir | basename }}"

    - name: Print path
      debug:
        var: path

    - name: Clear receive dir
      file:
        path: "{{ path }}"
        state: absent
      register: clear_result
      ignore_errors: true

    - name: Make receive dir
      file:
        path: "{{ path }}"
        state: directory
        mode: 0755
      register: file_result
      ignore_errors: true

    - block:
        - name: Skip when make receive dir fail
          debug:
            msg: "{{ 'Make receive dir ' + path + ' fail, end host.' }}"

        - name: end_host
          meta: end_host
      when: file_result.failed == 1

    - block:
        - name: compose src_list
          set_fact:
            src_list: "{{ src_list | default([]) + [{ 'src': find_result_files_var.path }] }}"
          loop: "{{ find_result.files }}"
          loop_control:
            loop_var: find_result_files_var

        - name: debug src_list
          debug:
            var: src_list

        - name: Transfer image to target_system
          ibm.power_ibmi.ibmi_synchronize_files:
            dest: "{{ path }}"
            src_list: "{{ src_list }}"
          delegate_to: "{{ repo_server }}"
          register: sync_result

        - name: Print transfer
          debug:
            var: sync_result

        - block:
            - name: skip when transfer failed
              debug:
                msg: "One or more ptf group file transfer failed, quit apply ptf group action."

            - name: delete the dest file dir
              file:
                path: "{{ path }}"
                state: absent
              ignore_errors: true
              when: deletefile

            - name: end_host
              meta: end_host
          when: sync_result.fail_list != []

        - name: Get the home dir on target server
          shell: 'echo $HOME'
          register: home_dir

        - name: Compose path
          set_fact:
            path: "{{ path | regex_replace('~', home_dir.stdout) }}"
          when: path | regex_search("^~")

        - name: debug path
          debug:
            var: path

        - block:
            - name: Apply PTF group
              ibm.power_ibmi.ibmi_fix_imgclg:
                src: '{{ path }}'
              register: apply_result
              ignore_errors: true

            - name: Print apply result
              debug:
                var: apply_result

            - name: Print apply result
              debug:
                msg: "PTF Group applied fail. Please see above job log"
              when: apply_result.rc != 0

            - name: Print apply result
              debug:
                msg: "PTF Group applied succesfully."
              when: apply_result.rc == 0

            - name: delete the dest file dir
              file:
                path: "{{ path }}"
                state: absent
              ignore_errors: true
              when: deletefile

             - name: Query the list of ptfs which requires an IPL
                ibmi_sql_query:
                  sql: "SELECT PTF_IDENTIFIER, PTF_PRODUCT_ID, PTF_IPL_ACTION, A.*
                  FROM QSYS2.PTF_INFO A
                  WHERE PTF_IPL_ACTION <> 'NONE'"
                register: query_ptf_result

              - name: Debug msg
                debug:
                  msg: 'No PTFs require an IPL.'
                when: query_ptf_result.row | length == 0

              - block:
                  - name: Display ptf list which require an IPL
                    debug: var=query_ptf_result.row

                  - name: Debug msg
                    debug:
                      msg: 'At least one PTF requires an IPL, but auto_ipl is false. Please IPL the system manually.'
                    when: not auto_ipl

                  - name: Debug msg
                    debug:
                      msg: 'At least one PTF requires an IPL and auto_ipl is true. The system is going to be IPLed soon.'
                    when: auto_ipl | bool

                  - name: Reboot the system immediately if auto_ipl is set to true and at least one PTF requires an IPL
                    ibmi_reboot:
                      pre_reboot_delay: '{{ pre_reboot_delay }}'
                      post_reboot_delay: '{{ post_reboot_delay }}'
                      reboot_timeout: '{{ reboot_timeout }}'
                      connect_timeout: '{{ connect_timeout }}'
                      test_command: '{{ test_command }}'
                      msg: '{{ msg }}'
                      how_to_end: '{{ how_to_end }}'
                      controlled_end_delay_time: '{{ controlled_end_delay_time }}'
                      reboot_type: '{{ reboot_type }}'
                      ipl_source: '{{ ipl_source }}'
                      end_subsystem_option: '{{ end_subsystem_option }}'
                      timeout_option: '{{ timeout_option }}'
                    when: auto_ipl | bool
                  when: query_ptf_result.row | length > 0
          when: sync_result.fail_list == []

      when: file_result.failed == 0
